apiVersion: apps/v1
kind: Deployment
metadata:
  name: estudio
  labels:
    app.kubernetes.io/name: estudio
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: estudio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: estudio
    spec:
      initContainers:
        - name: estudio-migrate
          image: ghcr.io/wagoid/estudio-up:v1.13.5 # {x-release-please-version}
          command: ['npm']
          args: ['run', 'migrate']
          envFrom:
            - secretRef:
                name: estudio-secrets
          env:
            - name: POSTGRES_HOST
              value: cnpg-cluster-postgres-cluster-rw.cnpg-database
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DATABASE
              value: estudio
            - name: POSTGRES_USER
              value: estudio
      containers:
        - name: estudio
          image: ghcr.io/wagoid/estudio-up:v1.13.5 # {x-release-please-version}
          command: ['/usr/bin/tini']
          args: ['--', '/app/node_modules/.bin/next', 'start']
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: estudio-secrets
          env:
            - name: POSTGRES_HOST
              value: cnpg-cluster-postgres-cluster-rw.cnpg-database
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DATABASE
              value: estudio
            - name: POSTGRES_USER
              value: estudio
            - name: AUTH_URL
              value: https://estudio.uptec.top
            - name: AUTHENTIK_URL
              value: https://acesso.uptec.top
            - name: AWS_BUCKET_NAME
              value: estudio
            - name: AWS_REGION
              value: local
            - name: AWS_S3_ENDPOINT_URL
              value: http://minio.minio:9000
            - name: AWS_S3_FORCE_PATH_STYLE
              value: 'true'
            - name: AWS_S3_PUBLIC_URL
              value: https://storage.wagdev.top
            - name: TTS_URL
              value: http://tts:7851
