apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: estudio
  namespace: apps
  labels:
    app: estudio
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - estudio.uptec.top
      secretName: estudio-tls
  rules:
    - host: estudio.uptec.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: estudio
                port:
                  number: 3000
